### PR TITLE
refactor bw variation/wireless comments (attempt at #142)

### PR DESCRIPTION
**Pull request by GrumpyOldTroll**

### CODE REVIEW

**Comment by SpencerDawkins** [comment]
Discussion from editor's conference call: 

- Can we provide a reference for useful properties?
- Network analytics, application analytics, or both? Currently application analytics, which is OK. Is that clear enough?
- Who is supposed to notice changes from an expected baseline?
- Is mentioning QLOG helpful? 
- Have we said clearly enough that baselines themselves can fluctuate, before the kinds of path characteristic changes we're talking about kick in?

**Comment by SpencerDawkins** [comment]
close #142

**Review by SpencerDawkins — APPROVED** [review]
@GrumpyOldTroll - this is good enough to merge. One suggestion - for 

> There are many reasons why path characteristics might change suddenly, for example:

perhaps 

> There are many reasons why path characteristics might change in normal operation. For example:

I'm still trying to distinguish between "a baseline value" and "a baseline pattern", which is what we're actually talking about. Would saying "baseline pattern" in the document be helpful?

**Comment by GrumpyOldTroll** [comment]
I think just "baseline" is clear enough to me, in context with this section listing some relevant stats.  I guess "baseline pattern of some relevant statistics" is maybe more precise, but I'm not sure "baseline pattern" really gets there.

**Review by SpencerDawkins — APPROVED** [review]
This works for me. I'll merge it.

**Pull request merged**
