### PR TITLE
first attempt at text for DISCUSS

### PR DESCRIPTION
**Pull request by GrumpyOldTroll**

### CODE REVIEW

**Comment by GrumpyOldTroll** [comment]
One note about this edit:

~~~
- ### Impact of Global Pandemic {{IABcovid}}
+ ### Impact of Global Pandemic
~~~

My local build failed with this (from a fresh clone):

~~~
(ietf2) bur-mp42v:mops2 jholland$ make
Makefile:2: lib/main.mk: No such file or directory
git clone -q --depth 10  \
	    -b main https://github.com/martinthomson/i-d-template lib
lib/main.mk:43: Forcing rebuild of .targets.mk
lib/main.mk:55: .targets.mk: No such file or directory
cat draft-ietf-mops-streaming-opcons.md  | kramdown-rfc2629 --v3 | lib/trace.sh draft-ietf-mops-streaming-opcons.xml -s venue lib/add-note.py | lib/trace.sh draft-ietf-mops-streaming-opcons.xml -s v2v3 xml2rfc -q -s 'Setting consensus="true" for IETF STD document' --rfc-base-url https://www.rfc-editor.org/rfc/ --id-base-url https://datatracker.ietf.org/doc/html/ --cache=/Users/jholland/.cache/xml2rfc --v2v3 /dev/stdin -o /dev/stdout >draft-ietf-mops-streaming-opcons.xml
*** attributes left {"stream"=>"IETF"}!
lib/trace.sh draft-ietf-mops-streaming-opcons.txt -s xml2rfc-txt xml2rfc -q -s 'Setting consensus="true" for IETF STD document' --rfc-base-url https://www.rfc-editor.org/rfc/ --id-base-url https://datatracker.ietf.org/doc/html/ --cache=/Users/jholland/.cache/xml2rfc draft-ietf-mops-streaming-opcons.xml -o draft-ietf-mops-streaming-opcons.txt --text --no-pagination
draft-ietf-mops-streaming-opcons.xml(255): Error: Did not expect element xref there, at /rfc/middle/section[3]/section[6]/section[2]/xref
draft-ietf-mops-streaming-opcons.xml(255): Error: Element section has extra content: xref, at /rfc/middle/section[3]/section[6]/section[2]/xref
/Users/jholland/src/github/mops2/draft-ietf-mops-streaming-opcons.xml(14): Error: Invalid document before running preptool.
Unable to complete processing draft-ietf-mops-streaming-opcons.xml
make: *** [draft-ietf-mops-streaming-opcons.txt] Error 1
~~~

In line 255 of the xml, it has the xref here:

~~~
         <name>Impact of Global Pandemic</name>
          <xref target="IABcovid" format="default"/>
~~~

Thus the issue in my local build went away when I made the above change.

I'm not sure why this passed build in the repo, it looks to me like it's expected to fail?  But anyway, that's why I have that part, and I'm not sure we wanted a reference in the title anyway.  Probably should be in a different PR, but I'm rushing out the door and wanted the reviews, but also wanted to make it build first...

**Comment by SpencerDawkins** [comment]
@GrumpyOldTroll - My apologies for driving you a little bit nuttier. 

> One note about this edit:
> 
> ```
> - ### Impact of Global Pandemic {{IABcovid}}
> + ### Impact of Global Pandemic
> ```

I tend to add cross-ref targets on pretty much everything, but (of course) that one should have been 

> ### Impact of Global Pandemic **{#IABcovid}**

**Review by SpencerDawkins — APPROVED** [review]
@GrumpyOldTroll - this PR looks plausible to me, but we'll see what @rdanyliw says - he is, after all, the Discuss holder :stuck_out_tongue_winking_eye:.

I do have a couple of nits. 

In this text, 

> This provides a strong incentive for advertisers to gain access to the data necessary to perform behavioral targeting, leading some to engage in what amounts to a pervasive monitoring attack ({{RFC7258}}) based on user tracking in order to collect the relevant data, 

- Is "what amounts to" the right phrase? It seems quite direct. Perhaps "can be considered"? 
- it might be worth mentioning explicitly that collecting this information without user consent is the problem. So, insert "without user consent" at the appropriate place?

In this text (which existed before the PR), 

> this market historically has had incidents of ad fraud (misreporting of ad delivery to end users for financial gain)

is there a decent reference that could be added?

In this text,

> some SSPs have required the use of specific players

I'd suggest 

> some SSPs have required the use of specific media players

**Comment by GrumpyOldTroll** [comment]
> I tend to add cross-ref targets on pretty much everything, but (of course) that one should have been
> 
> `### Impact of Global Pandemic {#IABcovid}`

I tried that, but it also failed since IABcovid was already a named reference in the reference section, and the one place it was used seemed to be referring to that.  So I thought it better to remove the tag.

**Comment by GrumpyOldTroll** [comment]
> > This provides a strong incentive for advertisers to gain access to the data necessary to perform behavioral targeting, leading some to engage in what amounts to a pervasive monitoring attack ({{RFC7258}}) based on user tracking in order to collect the relevant data,
> 
> * Is "what amounts to" the right phrase? It seems quite direct. Perhaps "can be considered"?
> * it might be worth mentioning explicitly that collecting this information without user consent is the problem. So, insert "without user consent" at the appropriate place?

Maybe, but on my reading of 7258, making the collection overt instead of covert and requiring consent is one of the mitigations, but does not change the notion of the pervasive monitoring behavior matching the technical definition of the attack as they describe it.  I landed on this text after looking for something softer but then considering a few quotes like these from 7258:

~~~
   In particular, the term "attack", used technically, implies nothing
   about the motivation of the actor mounting the attack.  The
   motivation for PM can range from non-targeted nation-state
   surveillance, to legal but privacy-unfriendly purposes by commercial
   enterprises, to illegal actions by criminals.  The same techniques to
   achieve PM can be used regardless of motivation.  Thus, we cannot
   defend against the most nefarious actors while allowing monitoring by
   other actors no matter how benevolent some might consider them to be,
   since the actions required of the attacker are indistinguishable from
   other attacks.  The motivation for PM is, therefore, not relevant for
   how PM is mitigated in IETF protocols.
~~~

~~~
   The term "attack" is used here in a technical sense that differs
   somewhat from common English usage.  In common English usage, an
   attack is an aggressive action perpetrated by an opponent, intended
   to enforce the opponent's will on the attacked party.  The term is
   used here to refer to behavior that subverts the intent of
   communicating parties without the agreement of those parties.  An
   attack may change the content of the communication, record the
   content or external characteristics of the communication, or through
   correlation with other communication events, reveal information the
   parties did not intend to be revealed.
~~~

I'm happy to take suggestions but it seemed to me that if there are broad segments of people who do not realize that agreeing to cookie use means agreeing to expose much of their browsing history to multiple parties, then the best description based on existing terms is to call it a PM attack.

> In this text (which existed before the PR),
> 
> > this market historically has had incidents of ad fraud (misreporting of ad delivery to end users for financial gain)
> 
> is there a decent reference that could be added?

Yeah, good point.  Maybe this? https://www.mdpi.com/2624-800X/1/4/39

> In this text,
> 
> > some SSPs have required the use of specific players
> 
> I'd suggest
> 
> > some SSPs have required the use of specific media players

Yes, that's better.  Thanks.  That'll be in the rev...

**Comment by SpencerDawkins** [comment]
> > > This provides a strong incentive for advertisers to gain access to the data necessary to perform behavioral targeting, leading some to engage in what amounts to a pervasive monitoring attack ({{RFC7258}}) based on user tracking in order to collect the relevant data,
> > 
> > 
> > 
> > * Is "what amounts to" the right phrase? It seems quite direct. Perhaps "can be considered"?
> > * it might be worth mentioning explicitly that collecting this information without user consent is the problem. So, insert "without user consent" at the appropriate place?
> 
> Maybe, but on my reading of 7258, making the collection overt instead of covert and requiring consent is one of the mitigations, but does not change the notion of the pervasive monitoring behavior matching the technical definition of the attack as they describe it. I landed on this text after looking for something softer but then considering a few quotes like these from 7258:
> 
> ```
>    In particular, the term "attack", used technically, implies nothing
>    about the motivation of the actor mounting the attack.  The
>    motivation for PM can range from non-targeted nation-state
>    surveillance, to legal but privacy-unfriendly purposes by commercial
>    enterprises, to illegal actions by criminals.  The same techniques to
>    achieve PM can be used regardless of motivation.  Thus, we cannot
>    defend against the most nefarious actors while allowing monitoring by
>    other actors no matter how benevolent some might consider them to be,
>    since the actions required of the attacker are indistinguishable from
>    other attacks.  The motivation for PM is, therefore, not relevant for
>    how PM is mitigated in IETF protocols.
> ```
> 
> ```
>    The term "attack" is used here in a technical sense that differs
>    somewhat from common English usage.  In common English usage, an
>    attack is an aggressive action perpetrated by an opponent, intended
>    to enforce the opponent's will on the attacked party.  The term is
>    used here to refer to behavior that subverts the intent of
>    communicating parties without the agreement of those parties.  An
>    attack may change the content of the communication, record the
>    content or external characteristics of the communication, or through
>    correlation with other communication events, reveal information the
>    parties did not intend to be revealed.
> ```
> 
> I'm happy to take suggestions but it seemed to me that if there are broad segments of people who do not realize that agreeing to cookie use means agreeing to expose much of their browsing history to multiple parties, then the best description based on existing terms is to call it a PM attack.

A couple of things here:

- I agree with your reading of RFC 7258 (and, looking back at https://datatracker.ietf.org/doc/rfc7258/ballot/, I actually balloted on it - 2014 was a long time ago, so I'd forgotten). 
- I think it's consistent with RFC 7258 to say "This provides a strong incentive for advertisers to gain access to the data necessary to perform behavioral targeting, leading some to engage in what _is indistinguishable from_ a pervasive monitoring attack ({{RFC7258}}) based on user tracking in order to collect the relevant data,"

I understand you to say that since everyone accepts cookies, whether they should do so or not, so that doesn't count as informed consent, and the use of cookies to indicate consent doesn't change the characterization of what advertisers are doing - it's still indistinguishable from an attack, Is that right? 

If I'm tracking you correctly, perhaps that's a point worth making (not in those words, perhaps). 

But let's wait and see what @rdanyliw says - he is, after all, the Discuss holder 😜.

> 
> > In this text (which existed before the PR),
> > > this market historically has had incidents of ad fraud (misreporting of ad delivery to end users for financial gain)
> > 
> > 
> > is there a decent reference that could be added?
> 
> Yeah, good point. Maybe this? https://www.mdpi.com/2624-800X/1/4/39

That's EXACTLY what I was hoping for!

**Comment by SpencerDawkins** [comment]
@GrumpyOldTroll - thanks for pushing back and making me think about my suggestion on RFC 7258. I reviewed your changes and they look fine.

**Comment by SpencerDawkins** [comment]
@rdanyliw - have you had a chance to look at this PR?

**Pull request merged**
